### ISSUE TITLE
Binaries and build instructions missing?

### ISSUE THREAD

**Issue by BMaxV** [charalambos/3DUNDERWORLD-Structured-Light-Scanner#2]
Hello,

I thought I'd try to use your software, but the official download from your website doesn't contain binaries and there are no obvious build instructions?

Also, this is a little beside the point, but there is also no license I can see? I mean the code is licensed on your website under a creative commons lincense but on the whole it's far from obvious if that applies to just the code, or also the binaries or manual.

**Comment by RobertaRavanelli** [comment]
Hello,

I'm not involved with this project (charalambos@poullis.org is the
repository owner).

However I've ported this algorithm inside OpenCV within the 2015 Google
Summer of Code international program.

You can find the code and a dataset at the following links:

https://github.com/Itseez/opencv_contrib/tree/master/modules/structured_light

https://github.com/RobertaRavanelli/GSoC2015_statue_dataset

Best regards,

Roberta

2016-06-25 12:06 GMT+02:00 BMaxV notifications@github.com:

> Hello,
> 
> I thought I'd try to use your software, but the official download from
> your website doesn't contain binaries and there are no obvious build
> instructions?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/theICTlab/3DUNDERWORLD-Structured-Light-Scanner/issues/2,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHNXpEIKAwUcjNAO_CstrSBCzLp2gujkks5qPP2QgaJpZM4I-UB5
> .

## 

Roberta Ravanelli, *PhD Student *
Geodesy and Geomatics Division
University of Rome "La Sapienza"
Via Eudossiana, 18 - 00184 Rome Italy
E-mail roberta.ravanelli@uniroma1.it

## 

---

INVESTI SUL FUTURO, FAI CRESCERE L’UNIVERSITÀ:

_DONA IL 5 PER MILLE ALLA SAPIENZA_

CODICE FISCALE _80209930587_

**Comment by v3c70r** [comment]
Hello, 

We are currently working on a newer version of SLS. Including refactoring of the base code as well as a faster implementation on GPU with CUDA. We are planing to publish it soon. 

Best,
Tsing

**Comment by Neon22** [comment]
@RobertaRavanelli fantastic news. Thanks!
Is it exposed to the python wrapper also ?

**Comment by RobertaRavanelli** [comment]
Yes, it should have been exposed to python and java wrapper.

2016-06-26 23:59 GMT+02:00 Neon22 notifications@github.com:

> @RobertaRavanelli https://github.com/RobertaRavanelli fantastic news.
> Thanks!
> Is it exposed to the python wrapper also ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/theICTlab/3DUNDERWORLD-Structured-Light-Scanner/issues/2#issuecomment-228625538,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHNXpMqs_UouUcF94q2G9YbtzV6rqYpcks5qPvZNgaJpZM4I-UB5
> .

## 

Roberta Ravanelli, *PhD Student *
Geodesy and Geomatics Division
University of Rome "La Sapienza"
Via Eudossiana, 18 - 00184 Rome Italy
E-mail roberta.ravanelli@uniroma1.it

## 

---

INVESTI SUL FUTURO, FAI CRESCERE L’UNIVERSITÀ:

_DONA IL 5 PER MILLE ALLA SAPIENZA_

CODICE FISCALE _80209930587_
